version: "3.9"

services:
  api:
    build: .
    container_name: PlaylistService
    networks:
      - network
    hostname: PlaylistServiceApplication
    depends_on:
      -   postgres
    environment:
      - POSTGRES_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}?sslmode=disable
    ports:
      - "50051:50051"
    restart: on-failure

  postgres:
    image: postgres:15-alpine
    container_name: PlaylistDatabase
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: PlaylistService
      PGDATA: /data/postgres
    networks:
      - network
    ports:
      - "5432:5432"

networks:
  network:
    driver: bridge